export const TARGET_TYPES = {
  SPEED: 'SPEED',
  HEART_RATE: 'HEART_RATE',
  OPEN: 'OPEN',
  CADENCE: 'CADENCE',
  POWER: 'POWER',
  GRADE: 'GRADE',
  RESISTANCE: 'RESISTANCE',
  POWER_3S: 'POWER_3S',
  POWER_10S: 'POWER_10S',
  POWER_30S: 'POWER_30S',
  POWER_LAP: 'POWER_LAP',
  SWIM_STROKE: 'SWIM_STROKE',
  SPEED_LAP: 'SPEED_LAP',
  HEART_RATE_LAP: 'HEART_RATE_LAP',
  PACE: 'PACE'
}
